### ISSUE TITLE
Estruturar documentação

### ISSUE THREAD

**Issue by gustavopergola** [jpsmedeiros/Xadrez-6x6#11]
inicializar a documentação base

**Comment by Lice23** [comment]
O relatório deve conter:

- [x] Explicação das regras do jogo (como funciona).
- [x] Formalização do problema: estados, ações, modelo de transição, teste para nó terminal, função de avaliação.
- [x] Justificativa para a escolha do jogo (o que o torna desafiante para ser resolvido por um algoritmo de IA; em qual categoria de ambiente ele está contido).
- [x] Documentação associada à implementação.
- [x] Resultados obtidos.
- [x] Introdução, Conclusão e Referências bibliográficas.
- [x] Todas as instruções para a execução do trabalho, bem como comentários ao longo do código, devem ser incluídos.
Por favor, especificar o nome de todos os componentes.

**Comment by Lice23** [comment]
https://drive.google.com/file/d/1YRnuXB0s8avpx6iiLlgjHFHMXmGIH-D4/view
(link da especificação do trabalho do classroom)

**Comment by Lice23** [comment]
https://docs.google.com/document/d/1tEBfTf0k4E7AyRiQmmTO6AQ2Ocicn42wAtKNdlosDkI/edit?usp=sharing

Link do relatório final. Utilizar email da UFF para acessar.
