### ISSUE TITLE
gameIsOver precisa ser refeito

### ISSUE THREAD

**Issue by Andrelpoj** [jpsmedeiros/Xadrez-6x6#19]
Precisamos evitar que a árvore tenha altura infinita. Deve-se prevenir que os jogadores possam fazer movimentos repetidos e manter o jogo rodando para sempre.

**Comment by gustavopergola** [comment]
vou botar um segundo contador de jogadas no State pra checar quantas jogadas foram feitas naquele estado sem captura de peças.. visto que o contador de jogadas que já tem está sendo usado para checar o cutoff
